development:
  adapter: mysql2
  database: postif_development
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql2
  database: postif_test
  username: root
  password:
  encoding: utf8

production:
  adapter: mysql2
  database: postif_production
  username: root
  password: 
  encoding: utf8
